In [18]:
import fiscalpy as fp
import pandas as pd
from fiscalpy import limpieza_ingresos_territoriales
from fiscalpy import columnas_ingresos_territoriales

In [7]:
df = pd.read_excel("C:/Users/SebasM/OneDrive/Documentos/try/ejec_ing_25.xlsx")

In [8]:
df

,Año Vigencia,Periodo,Cadena Periodo,Código DANE,Código FUT,Entidad,Tipo de Entidad,Departamento,Region,SubRegion,...,Código Política Pública,Política Pública,Norma,Código Tipo de Norma,Tipo de Norma,Recaudo Vigencia Anterior Sin Fondos,Recaudo Vigencia Antgerior Con Fondos,Recaudo Vigencia Actual Sin Fondos,Recaudo Vigencia Actual Con Fondos,Total Recaudo
0,2025,Anual (Enero - Diciembre),11212,5000,110505000,Antioquia,Departamento,Antioquia,Eje cafetero,...,...,,...,...,,...,0,0,971948680698,7468580978058,8440529658756
1,2025,Anual (Enero - Diciembre),11212,5000,110505000,Antioquia,Departamento,Antioquia,Eje cafetero,...,...,,...,...,,...,0,0,892571122872,5826226788305,6718797911177
2,2025,Anual (Enero - Diciembre),11212,5000,110505000,Antioquia,Departamento,Antioquia,Eje cafetero,...,...,,...,...,,...,0,0,274700679776,2109287234839,2383987914615
3,2025,Anual (Enero - Diciembre),11212,5000,110505000,Antioquia,Departamento,Antioquia,Eje cafetero,...,...,,...,...,,...,0,0,14275075292,746092325179,760367400471
4,2025,Anual (Enero - Diciembre),11212,5000,110505000,Antioquia,Departamento,Antioquia,Eje cafetero,...,...,0,NO APLICA,NaN,0.0,NO APLICA,0,0,0,528151512018,528151512018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155420,2025,Anual (Enero - Diciembre),11212,27493,923273478,Nuevo Belén de Bajirá,Municipio,Chocó,Pacífica,NaN,...,0,NO APLICA,0,0.0,NO APLICA,0,1038976136,0,0,1038976136
155421,2025,Anual (Enero - Diciembre),11212,27493,923273478,Nuevo Belén de Bajirá,Municipio,Chocó,Pacífica,NaN,...,0,NO APLICA,0,0.0,NO APLICA,0,173440206,0,0,173440206
155422,2025,Anual (Enero - Diciembre),11212,27493,923273478,Nuevo Belén de Bajirá,Municipio,Chocó,Pacífica,NaN,...,0,NO APLICA,0,0.0,NO APLICA,0,3852023421,0,0,3852023421
155423,2025,Anual (Enero - Diciembre),11212,27493,923273478,Nuevo Belén de Bajirá,Municipio,Chocó,Pacífica,NaN,...,,...,...,,...,0,0,0,3308659,3308659
155424,2025,Anual (Enero - Diciembre),11212,27493,923273478,Nuevo Belén de Bajirá,Municipio,Chocó,Pacífica,NaN,...,0,NO APLICA,0,0.0,NO APLICA,0,0,0,3308659,3308659

In [9]:
norm_data = limpieza_ingresos_territoriales(df, tipo='ejecucion')

c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS CORRIENTES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS TRIBUTARIOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTOS DIRECTOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO SOBRE VEHICULOS AUTOMOTORES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO DE REGISTRO - CAMARAS DE COMERCIO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO AL CONSUMO DE VINOS, APERITIVOS Y SIMILARES - COMPONENTE ESPECIFICO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO AL CONSUMO DE VINOS, APERITIVOS Y SIMILARES - COMPONENTE ESPECÍFICO DE PRODUCCIÓN NACIONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PARTICIPACION POR EL CONSUMO DE LICORES DESTILADOS INTRODUCIDOS DE PRODUCCION NACIONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PARTICIPACION POR EL CONSUMO DE LICORES DESTILADOS INTRODUCIDOS DE PRODUCCION EXTRANJERA RECAUDADO POR FONDO CUENTA DE LA FND' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]

In [34]:
norm_data

,Año Vigencia,Código DANE,Entidad,Tipo de Entidad,Departamento,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,Total Recaudo
0,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,9869258588
1,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,33881133796
2,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES ESPECIALES,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,8592708866
3,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,29390411255
4,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",MULTAS Y SANCIONES,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,759528584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49317,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,861503388
49318,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RECURSOS DEL BALANCE,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,23486011655
49319,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,REINTEGROS Y OTROS RECURSOS NO APROPIADOS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,900000
49320,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RENDIMIENTOS FINANCIEROS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,366264489
49321,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RETIROS FONPET,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,2511882659

In [11]:
norm_data.to_excel("ejec_clean25.xlsx", index=False)

In [13]:
df_2 = pd.read_excel("C:/Users/SebasM/OneDrive/Documentos/try/2025_8_CUIPOA_PROGRAMACION_DE_INGRESOS.xlsx")

In [14]:
norm_data_1 = limpieza_ingresos_territoriales(df_2, tipo='programacion')

c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS CORRIENTES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'INGRESOS TRIBUTARIOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTOS DIRECTOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO SOBRE VEHICULOS AUTOMOTORES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO DE REGISTRO - CAMARAS DE COMERCIO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO AL CONSUMO DE VINOS, APERITIVOS Y SIMILARES - COMPONENTE ESPECIFICO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'IMPUESTO AL CONSUMO DE VINOS, APERITIVOS Y SIMILARES - COMPONENTE ESPECÍFICO DE PRODUCCIÓN NACIONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PARTICIPACION POR EL CONSUMO DE LICORES DESTILADOS INTRODUCIDOS DE PRODUCCION NACIONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:222: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PARTICIPACION POR EL CONSUMO DE LICORES DESTILADOS INTRODUCIDOS DE PRODUCCION EXTRANJERA RECAUDADO POR FONDO CUENTA DE LA FND' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]

In [16]:
norm_data_1.to_excel("prog_ing_clean25.xlsx", index=False)

In [22]:
norm_data_1

,Año Vigencia,Código DANE,Entidad,Tipo de Entidad,Departamento,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,Presupuesto Inicial,Presupuesto Definitivo
0,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,6658952379,10030300722
1,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,59415604565,41825235091
2,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES ESPECIALES,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,5982087000,8592708866
3,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,19257655017,19316251061
4,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",MULTAS Y SANCIONES,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,515386172,515386172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53260,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,94000000,94000000
53261,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,500000000,700000000
53262,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RECURSOS DEL BALANCE,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,0,23486011656
53263,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RENDIMIENTOS FINANCIEROS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,1,365160245
53264,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RETIROS FONPET,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,0,2511882659

In [31]:
norm_data_0 = columnas_ingresos_territoriales(norm_data_1)

In [32]:
norm_data_0

,Año Vigencia,Código DANE,Entidad,Tipo de Entidad,Departamento,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,Presupuesto Inicial,Presupuesto Definitivo,clas_ofpuj,clas_gen1,clas_gen2
0,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,6658952379,10030300722,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
1,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,59415604565,41825235091,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
2,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES ESPECIALES,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,5982087000,8592708866,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
3,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,19257655017,19316251061,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
4,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",MULTAS Y SANCIONES,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,515386172,515386172,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53260,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,SOBRETASA BOMBERIL,94000000,94000000,Sobretasa bomberil,Ingresos tributarios,Recursos propios
53261,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,500000000,700000000,Tasa prodeporte y recreacion,Ingresos tributarios,Recursos propios
53262,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RECURSOS DEL BALANCE,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,0,23486011656,Recursos del balance,Recursos de capital,Recursos de capital
53263,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RENDIMIENTOS FINANCIEROS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,1,365160245,Otros recursos de capital,Recursos de capital,Recursos de capital
53264,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,INGRESOS,RECURSOS DE CAPITAL,RETIROS FONPET,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,0,2511882659,Otros recursos de capital,Recursos de capital,Recursos de capital

In [33]:
norm_data_0.to_excel("pro_ing_clean27.xlsx", index=False)

In [35]:
norm_data_9 = columnas_ingresos_territoriales(norm_data)

In [36]:
norm_data_9

,Año Vigencia,Código DANE,Entidad,Tipo de Entidad,Departamento,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,Total Recaudo,clas_ofpuj,clas_gen1,clas_gen2
0,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,CONTRIBUCION DE VALORIZACION,9869258588,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
1,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES DIVERSAS,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,CONTRIBUCION ESPECIAL SOBRE CONTRATOS DE OBRAS...,33881133796,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
2,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,CONTRIBUCIONES,CONTRIBUCIONES ESPECIALES,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,CUOTA DE FISCALIZACION Y AUDITAJE,8592708866,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
3,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,INTERESES DE MORA,29390411255,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
4,2025,5000,Antioquia,Departamento,Antioquia,INGRESOS,INGRESOS CORRIENTES,INGRESOS NO TRIBUTARIOS,"MULTAS, SANCIONES E INTERESES DE MORA",MULTAS Y SANCIONES,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,MULTAS DE TRANSITO Y TRANSPORTE,759528584,"Tasas, multas y contribuciones",Ingresos no tributarios,Recursos propios
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49317,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,INGRESOS CORRIENTES,INGRESOS TRIBUTARIOS,IMPUESTOS INDIRECTOS,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,TASA PRODEPORTE Y RECREACION,861503388,Tasa prodeporte y recreacion,Ingresos tributarios,Recursos propios
49318,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RECURSOS DEL BALANCE,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,SUPERAVIT FISCAL,23486011655,Recursos del balance,Recursos de capital,Recursos de capital
49319,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,REINTEGROS Y OTROS RECURSOS NO APROPIADOS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,REINTEGROS,900000,Otros recursos de capital,Recursos de capital,Recursos de capital
49320,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RENDIMIENTOS FINANCIEROS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,DEPOSITOS,366264489,Otros recursos de capital,Recursos de capital,Recursos de capital
49321,2025,99773,Cumaribo,Municipio,Vichada,INGRESOS,RECURSOS DE CAPITAL,RETIROS FONPET,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,DEL EXCEDENTE DEL CUBRIMIENTO DEL PASIVO PENSI...,2511882659,Otros recursos de capital,Recursos de capital,Recursos de capital

In [37]:
norm_data_9.to_excel("eje_ing_clean25.xlsx", index = False)

In [42]:
norm_data_9["clas_gen2"]

0           Recursos propios
1           Recursos propios
2           Recursos propios
3           Recursos propios
4           Recursos propios
                ...
49317       Recursos propios
49318    Recursos de capital
49319    Recursos de capital
49320    Recursos de capital
49321    Recursos de capital
Name: clas_gen2, Length: 49322, dtype: object